#!/usr/bin/env node
// Copies the selectable theme fonts into public/fonts and writes src/fonts.css (@font-face rules).
// The families are the ones editors can pick in Strapi (Site - Theme); Radio Canada, the default,
// is declared in src/styles.css. Source: the @fontsource packages (latin subset covers es/en).
//   npm i --prefix /tmp/fonts @fontsource/inter @fontsource/poppins ...   (once)
//   node scripts/sync-fonts.mjs /tmp/fonts/node_modules/@fontsource
import { copyFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = process.argv[2];
if (!source) {
  throw new Error('Usage: node scripts/sync-fonts.mjs <path to node_modules/@fontsource>');
}

const FAMILIES = [
  ['inter', 'Inter'],
  ['poppins', 'Poppins'],
  ['montserrat', 'Montserrat'],
  ['dm-sans', 'DM Sans'],
  ['playfair-display', 'Playfair Display'],
  ['lora', 'Lora'],
  ['merriweather', 'Merriweather'],
];
const WEIGHTS = [400, 500, 600, 700];

mkdirSync(resolve(root, 'public/fonts'), { recursive: true });
let css = '/* Generated by scripts/sync-fonts.mjs. Selectable theme fonts (see Site - Theme in Strapi). */\n';
for (const [slug, family] of FAMILIES) {
  for (const weight of WEIGHTS) {
    const from = resolve(source, slug, 'files', `${slug}-latin-${weight}-normal.woff2`);
    if (!existsSync(from)) {
      throw new Error(`Missing ${from}`);
    }

    copyFileSync(from, resolve(root, 'public/fonts', `${slug}-${weight}.woff2`));
    css += `\n@font-face {\n  font-family: '${family}';\n  src: url('/fonts/${slug}-${weight}.woff2') format('woff2');\n  font-weight: ${weight};\n  font-style: normal;\n  font-display: swap;\n}\n`;
  }
}

writeFileSync(resolve(root, 'src/fonts.css'), css);
console.log(`[fonts] ${FAMILIES.length * WEIGHTS.length} files -> public/fonts, src/fonts.css`);
